// Offline unit tests; no real Auth, credentials, database calls or writes.
import fs from'node:fs';import assert from'node:assert/strict';import{projectSummary,loadLive,PREVIEW_URL,GARDEN_ID}from'../../core-v1/my-garden/data.mjs';
const g={id:GARDEN_ID,user_id:'unit-owner'},plant=(id='unit-a',extra={})=>({id,garden_profile_id:GARDEN_ID,user_id:g.user_id,name:id==='unit-a'?'Apple':'Monstera',profile_slug:id==='unit-a'?'apple':'monstera',status:'unassessed',archived:false,...extra}),task=(id,extra={})=>({id,garden_profile_id:GARDEN_ID,user_id:g.user_id,garden_plant_id:null,done:false,...extra});
const plants=()=>[plant(),plant('unit-b')],tests=[];async function test(name,fn){try{await fn();tests.push({name,pass:true})}catch(e){tests.push({name,pass:false,error:e.message})}}
await test('2 active DB records => 2 plants, 0 existing pending tasks, UNKNOWN attention and unread',()=>{const m=projectSummary(g,plants(),[]);assert.equal(m.plantCount,2);assert.equal(m.upcomingCount,0);assert.equal(m.attentionCount,null);assert.equal(m.notificationUnreadCount,null);assert.equal(m.description,'Apple · Monstera — not assessed')});
await test('empty garden does not reuse baked counts or plant names',()=>{const m=projectSummary(g,[],[]);assert.equal(m.plantCount,0);assert.equal(m.upcomingCount,0);assert(!/Rose|Lemon|Apple/.test(m.description));assert.equal(m.attentionCount,null)});
await test('same canonical species has distinct instance identities',()=>{const m=projectSummary(g,[plant(),plant('unit-b',{profile_slug:'apple'})],[]);assert.equal(m.plants.length,2);assert.notEqual(m.plants[0].id,m.plants[1].id)});
await test('completed tasks excluded; pending task linked to active plant included',()=>{const m=projectSummary(g,plants(),[task('t1'),task('t2',{done:true}),task('t3',{garden_plant_id:'unit-a'})]);assert.equal(m.upcomingCount,2)});
await test('archived plant and its tasks excluded from summary',()=>{const m=projectSummary(g,[plant('unit-a',{archived:true})],[task('t1',{garden_plant_id:'unit-a'})]);assert.equal(m.plantCount,0);assert.equal(m.upcomingCount,0)});
await test('unknown done state => UNKNOWN count, never zero',()=>assert.equal(projectSummary(g,plants(),[task('t1',{done:null})]).upcomingCount,null));
await test('stored healthy status never silently creates zero attention',()=>{const m=projectSummary(g,[plant('unit-a',{status:'healthy'})],[]);assert.equal(m.attentionCount,null);assert.equal(m.description,'Attention status not assessed')});
for(const [name,garden,ps,ts]of [
 ['wrong garden',{...g,id:'other'},plants(),[]],['missing owner',{...g,user_id:null},plants(),[]],['cross-user plant',g,[plant('a',{user_id:'other'})],[]],['cross-garden plant',g,[plant('a',{garden_profile_id:'other'})],[]],['duplicate plant',g,[plant(),plant()],[]],['missing plant name',g,[plant('a',{name:''})],[]],['missing canonical slug',g,[plant('a',{profile_slug:null})],[]],['missing archive state',g,[plant('a',{archived:null})],[]],['cross-user task',g,plants(),[task('t',{user_id:'other'})]],['cross-garden task',g,plants(),[task('t',{garden_profile_id:'other'})]],['missing linked plant',g,plants(),[task('t',{garden_plant_id:'absent'})]],['duplicate task',g,plants(),[task('t'),task('t')]],['null plants',g,null,[]],['null tasks',g,plants(),null]
])await test(name+' rejected',()=>assert.throws(()=>projectSummary(garden,ps,ts)));
function client(config={}){const calls=[];const results={garden_profiles:{status:200,error:null,data:g},garden_plants:{status:200,error:null,data:plants(),count:2},garden_tasks:{status:200,error:null,data:[],count:0},...config.results};return {calls,supabaseUrl:config.url??PREVIEW_URL,auth:{getUser:async()=>{calls.push('auth');return config.auth??{data:{user:{id:g.user_id,role:'authenticated'}},error:null}}},from(table){calls.push(table);const q={select(){return q},eq(){return q},order(){return q},range(){return q},maybeSingle(){return Promise.resolve(results[table])},then(resolve,reject){return Promise.resolve(results[table]).then(resolve,reject)}};return q}}}
await test('batched live loader uses 1 Auth + 3 table requests (modeled)',async()=>{const c=client(),m=await loadLive(c);assert.equal(m.counts.databaseReads,3);assert.equal(m.counts.authReads,1);assert.deepEqual(c.calls,['auth','garden_profiles','garden_plants','garden_tasks']);assert.equal(m.sourceMode,'live-authenticated')});
await test('foreign project rejected before any request',async()=>{const c=client({url:'https://foreign.invalid'});await assert.rejects(()=>loadLive(c));assert.equal(c.calls.length,0)});
await test('invalid auth prevents all table reads',async()=>{const c=client({auth:{data:{user:null},error:{message:'offline'}}});await assert.rejects(()=>loadLive(c));assert.deepEqual(c.calls,['auth'])});
await test('User B cannot use someone else garden response',async()=>{const c=client({auth:{data:{user:{id:'unit-b',role:'authenticated'}},error:null}});await assert.rejects(()=>loadLive(c));assert.deepEqual(c.calls,['auth','garden_profiles'])});
for(const [name,result]of [['network',{status:0,error:{message:'unit'},data:null,count:null}],['server',{status:500,error:{message:'unit'},data:null,count:null}],['truncated',{status:200,error:null,data:[],count:1}],['missing count',{status:200,error:null,data:[],count:null}],['oversized',{status:200,error:null,data:[],count:1001}]])await test(name+' task read cannot become a successful zero',async()=>{await assert.rejects(()=>loadLive(client({results:{garden_tasks:result}})))});
const report={mode:'OFFLINE_UNIT_ONLY',passed:tests.filter(t=>t.pass).length,total:tests.length,tests,actualNetworkCalls:0,liveRlsProof:false};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
