// Offline unit assertions. No network, authentication, database writes, or deploy.
import assert from 'node:assert/strict';import fs from'node:fs';import{projectRows,GARDEN_ID,loadLive}from'../../core-v1/my-garden/plants/data.mjs';
const garden={id:GARDEN_ID,user_id:'unit-owner',name:'unit'};
const media={primaryUrl:'https://example.invalid/exact-approved.jpg',imageStatus:'IMAGE_READY',sourceAssetId:'unit-approved',attributionRequired:true,attribution:'unit attribution'};
const catalog=()=>[{slug:'unit-plant',scientific_name:'Unit species',verification_state:'verified',media_status:'IMAGE_READY',media:{...media}}];
const plant=()=>({id:'unit-instance',garden_profile_id:GARDEN_ID,user_id:'unit-owner',profile_slug:'unit-plant',name:'Unit',scientific:'Unit species',status:'unassessed',mark:'unknown',archived:false,cover_media_id:null,garden_area_id:null,cover:null,area:null});
const results=[];const test=(name,fn)=>{try{fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}};
test('exact source produces unassessed plant without inventing area',()=>{const m=projectRows(garden,[plant()],catalog());assert.equal(m.cards[0].status,'unassessed');assert.equal(m.cards[0].areaName,null);assert.equal(m.cards[0].image.url,media.primaryUrl)});
test('two same-species instances retain different instance IDs',()=>{const m=projectRows(garden,[plant(),{...plant(),id:'unit-2'}],catalog());assert.equal(m.cards.length,2);assert.notEqual(m.cards[0].id,m.cards[1].id)});
for(const [name,patch]of [['wrong garden',{garden_profile_id:'other'}],['wrong owner',{user_id:'other'}],['missing canonical',{profile_slug:'missing'}],['scientific conflict',{scientific:'Other species'}],['missing name',{name:''}],['invalid archive',{archived:null}],['dangling personal cover',{cover_media_id:'missing'}],['dangling area',{garden_area_id:'missing'}]])test(name,()=>assert.throws(()=>projectRows(garden,[{...plant(),...patch}],catalog())));
for(const [name,change]of [['unverified',c=>c.verification_state='pending'],['missing ready state',c=>c.media_status='MISSING'],['design cutout',c=>c.media.kind='design_cutout'],['other canonical image',c=>c.media.canonicalPlantIdentity='other'],['unsafe URL',c=>c.media.primaryUrl='javascript:bad'],['missing attribution',c=>delete c.media.attribution]])test(name,()=>{const c=catalog();change(c[0]);assert.throws(()=>projectRows(garden,[plant()],c))});
test('duplicate plant IDs rejected',()=>assert.throws(()=>projectRows(garden,[plant(),plant()],catalog())));
test('empty garden gives zero active cards',()=>assert.equal(projectRows(garden,[],[]).activeCount,0));
test('archived record not rendered',()=>assert.equal(projectRows(garden,[{...plant(),archived:true}],catalog()).cards.length,0));
test('exact validated personal reference accepted',()=>{const p=plant();p.cover_media_id='media-1';p.cover={id:'media-1',user_id:p.user_id,garden_profile_id:GARDEN_ID,garden_plant_id:p.id,validation_state:'validated',purpose:'plant_profile',storage_bucket:'user-garden-media',storage_path:'unit/file.jpg'};assert.equal(projectRows(garden,[p],catalog()).cards[0].personal.id,'media-1');p.cover.garden_plant_id='other';assert.throws(()=>projectRows(garden,[p],catalog()))});
await assert.rejects(()=>loadLive({supabaseUrl:'https://other.invalid'}));results.push({name:'wrong Preview origin rejected before Auth',pass:true});
const report={mode:'OFFLINE_UNIT_TESTS',passed:results.filter(r=>r.pass).length,total:results.length,results,realNetworkRequests:0,liveAuthProof:false};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
